services:
  crossroads-web:
    container_name: crossroads.web
    image: crossroads-web:latest
    ports:
      - "80:8080"
      - "8402:8081"

  crossroads-api:
    container_name: crossroads.api
    image: crossroads-webapi:latest
    # PID and docker.sock allow for checking running container on docker host
    pid: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8403:8080"
      - "8404:8081"